version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1-2017-03-nanoserver
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Multi.sln && dotnet publish ./Multi.sln -c Release -o ./obj/Docker/publish"
